extends RefCounted
## The people, as pixels read from the Game_1 Art Direction page's people
## sheet (made by a script from the 8x picture; see sandbox/README.md).
## Each sprite: rows from the top down, one letter per pixel (PALETTE),
## "." clear; the bottom row is the feet, `anchor` the x of their middle.
## Builder is the sheet's builder without the block on the head; woodcutter
## and miner are the plain peasant in other colours.

const PALETTE := {
	"a": Color8(92, 58, 36),
	"b": Color8(230, 176, 138),
	"c": Color8(26, 22, 34),
	"d": Color8(168, 106, 76),
	"e": Color8(138, 90, 52),
	"f": Color8(58, 36, 24),
	"g": Color8(124, 118, 128),
	"h": Color8(87, 81, 96),
	"i": Color8(90, 30, 36),
	"j": Color8(74, 122, 56),
	"k": Color8(46, 82, 48),
	"l": Color8(69, 85, 138),
	"m": Color8(44, 53, 88),
	"n": Color8(184, 138, 84),
	"o": Color8(226, 212, 176),
	"p": Color8(163, 156, 152),
	"q": Color8(244, 241, 230),
	"r": Color8(214, 178, 104),
	"s": Color8(63, 122, 120),
	"t": Color8(242, 182, 64),
	"u": Color8(106, 58, 106),
	"v": Color8(201, 192, 176),
	"w": Color8(154, 48, 40),
	"x": Color8(29, 50, 34),
	"y": Color8(255, 233, 160),
	"z": Color8(208, 88, 44),
	"A": Color8(58, 53, 64),
}

const SPRITES := {
	"peasant": {"anchor": 4, "rows": [
		"..aaa...",
		".aaaaa..",
		".aabbb..",
		".abbcb..",
		"..bbbb..",
		"...dd...",
		".eeeee..",
		"eeeeaee.",
		"eaeeaeeb",
		"b.eaeee.",
		"..ffff..",
		"..eeea..",
		"..eaaa..",
		"..f..f..",
		"..f..f..",
		".cc..cc.",
	]},
	"builder": {"anchor": 4, "rows": [
		"..fff...",
		".fffff..",
		".ffbbb..",
		".fbbcb..",
		"..bbbb..",
		"...dd...",
		".ggggg..",
		"gggghgg.",
		"ghgghggb",
		"b.ghggg.",
		"..ffff..",
		"..gggh..",
		"..ghhh..",
		"..f..f..",
		"..f..f..",
		".cc..cc.",
	]},
	"woodcutter": {"anchor": 4, "rows": [
		"..iii...",
		".iiiii..",
		".iibbb..",
		".ibbcb..",
		"..bbbb..",
		"...dd...",
		".jjjjj..",
		"jjjjkjj.",
		"jkjjkjjb",
		"b.jkjjj.",
		"..ffff..",
		"..jjjk..",
		"..jkkk..",
		"..f..f..",
		"..f..f..",
		".cc..cc.",
	]},
	"miner": {"anchor": 4, "rows": [
		"..aaa...",
		".aaaaa..",
		".aabbb..",
		".abbcb..",
		"..bbbb..",
		"...dd...",
		".lllll..",
		"llllmll.",
		"lmllmllb",
		"b.lmlll.",
		"..ffff..",
		"..lllm..",
		"..lmmm..",
		"..f..f..",
		"..f..f..",
		".cc..cc.",
	]},
	"crafter": {"anchor": 4, "rows": [
		"..nnn...",
		".nnnnn..",
		".nnbbb..",
		".nbbcb..",
		"..bbbb..",
		"...dd...",
		".ooooo..",
		"oooopoo.",
		"opqqqoob",
		"b.qqqoo.",
		"..qqqf..",
		"..qqqp..",
		"..oppp..",
		"..f..f..",
		"..f..f..",
		".cc..cc.",
	]},
	"forager": {"anchor": 4, "rows": [
		".rrrrr..",
		"rrrrrrr.",
		".aaaaa..",
		".aabbb..",
		".abbcb..",
		"..bbbb..",
		"...dd...",
		".sssss..",
		"ssssmss.",
		"smssmssb",
		"b.smsss.",
		"..ffff..",
		"..sssm..",
		"..smmm..",
		"..f..f..",
		"..f..f..",
		".cc..cc.",
	]},
	"noble": {"anchor": 4, "rows": [
		".t.t.t..",
		".ttttt..",
		"..ttt...",
		".ttttt..",
		".ttbbb..",
		".tbbcb..",
		"..bbbb..",
		"...dd...",
		".uuuuu..",
		"uuuumuu.",
		"umuumuub",
		"b.umuuu.",
		"..ffff..",
		"..uuum..",
		"..ummm..",
		"..f..f..",
		"..f..f..",
		".cc..cc.",
	]},
	"guard": {"anchor": 4, "rows": [
		".......v",
		".......p",
		".......a",
		"..pppp.a",
		".pvvvvpa",
		".pffffpa",
		".ffbbb.a",
		".fbbcb.a",
		"..bbbb.a",
		"...dd..a",
		".wwwww.a",
		"wwwwiwwa",
		"wiwwiwwa",
		"b.wiwwwa",
		"..ffff.a",
		"..wwwi.a",
		"..wiii.a",
		"..f..f.a",
		"..f..f.a",
		".cc..cc.",
	]},
	"hunter": {"anchor": 4, "rows": [
		"..kkk....",
		".kkkkk...",
		".kaaaa...",
		".aabbb...",
		".abbcb...",
		"..bbbb..e",
		"...dd..e.",
		".kkkkke..",
		"kkkkxke..",
		"kxkkxkeb.",
		"b.kxkkke.",
		"..ffff..e",
		"..kkkx...",
		"..kxxx...",
		"..f..f...",
		"..f..f...",
		".cc..cc..",
	]},
	"bandit": {"anchor": 4, "rows": [
		"..ccc....",
		".ccccc..y",
		".ccbbb..t",
		".cbbcb..z",
		"..bcccc.a",
		"...dd...a",
		".aaaaa..a",
		"aaaafaa.a",
		"afaafaab.",
		"b.afaaa..",
		"..ffff...",
		"..aaaf...",
		"..afff...",
		"..f..f...",
		"..f..f...",
		".cc..cc..",
	]},
	"raider": {"anchor": 4, "rows": [
		"..pppp...",
		".pvvvvp..",
		".piiiip..",
		".iibbb...",
		".ibbcbpp.",
		"..bbbbppa",
		"...dd.p.a",
		".hhhhh..a",
		"hhhhAhh.a",
		"hAhhAhhba",
		"b.hAhhh..",
		"..ffff...",
		"..hhhA...",
		"..hAAA...",
		"..f..f...",
		"..f..f...",
		".cc..cc..",
	]},
	"warband": {"anchor": 6, "rows": [
		".........v",
		".........p",
		".....gg..a",
		"....gvvg.a",
		"...gvvvvga",
		"...gcggcga",
		"...ccbbb.a",
		"...cbbcb.a",
		"....bbbb.a",
		".....dd..a",
		"...ggggg.a",
		"wwwggghgga",
		"wtwhgghgga",
		"wtw.ghggga",
		"www.ffff.a",
		"....gggh.a",
		"....ghhh.a",
		"....f..f.a",
		"....f..f.a",
		"...cc..cc.",
	]},
	"child": {"anchor": 3, "rows": [
		"..aaa..",
		".aabbb.",
		".abbcb.",
		"..bbb..",
		".eeeee.",
		"beeaeeb",
		"..fff..",
		"..eaa..",
		"..f.f..",
		".cc.cc.",
	]},
	"hauler": {"anchor": 4, "rows": [
		"..aaa...",
		".aaaaa..",
		".aabbb..",
		".abbcb..",
		"..bbbb..",
		"...dd...",
		".eeeee..",
		"eeeeaee.",
		"eaeeaeeb",
		"b.eaeee.",
		"..ffff..",
		"..eeea..",
		"..eaaa..",
		"..f..f..",
		"..f..f..",
		".cc..cc.",
	]},
}

static var _cache := {}


## The sprite as a texture. Frame 0 stands; 1 and 2 lift the left or right
## foot (the shoe on the bottom row is left out), for walking.
static func texture(name: String, frame := 0) -> Texture2D:
	var key := "%s/%d" % [name, frame]
	if _cache.has(key):
		return _cache[key]
	var s: Dictionary = SPRITES[name]
	var rows: Array = s.rows
	var h := rows.size()
	var w: int = rows[0].length()
	var img := Image.create(w, h, false, Image.FORMAT_RGBA8)
	for y in h:
		var row: String = rows[y]
		for x in w:
			var c := row[x]
			if c == ".":
				continue
			if y == h - 1 and ((frame == 1 and x < s.anchor) or (frame == 2 and x > s.anchor)):
				continue
			img.set_pixel(x, y, PALETTE[c])
	var tex := ImageTexture.create_from_image(img)
	_cache[key] = tex
	return tex


## Where to draw the texture so its feet stand on (0, 0).
static func offset(name: String) -> Vector2:
	var s: Dictionary = SPRITES[name]
	return Vector2(-s.anchor, -s.rows.size())


static func height(name: String) -> int:
	return SPRITES[name].rows.size()
